/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pandora;

import javax.swing.DefaultListModel;
import javax.swing.JDialog;

/**
 *
 * @author dominikmocher
 */
public class RulesEditor extends javax.swing.JPanel {

    Boolean rolling;
    String collidesWith;
    String ownObject;
    int collisionAction;
    Game actualGame;
    
    /**
     * Creates new form RulesEditor
     * @param game
     */
    public RulesEditor(Game game) {
        initComponents();
        actualGame = game;
        this.rolling = false;
        
        if(game.getDiceEnabled())
        {
            MovementLabel.setText("Bewegung durch Würfeln");
            Movement.setVisible(false);
        }
        
        jList1.removeAll();
        DefaultListModel list = new DefaultListModel(); //stores information into jList
        
        for(int i = 0; i < game.getNumberOfPlayers(); i++)
        {
            list.addElement("Spieler " + i);
        }

        jList1.setModel(list); //fills data into jList
        
        //initialize ContactComboBox
        ContactObjectList.removeAllItems();
        //ComboBoxModel comboList = new ComboBoxModel(list.toArray());
        //ContactObjectList.setModel(comboList);
        for(int i = 0; i < list.getSize(); i++)
        {
          ContactObjectList.addItem(list.toArray()[i]);
        }
        
        ContactActionBox.removeAllItems();
        String possible_actions[] = {"schlagen", "ignorieren", "überspringen", "nicht ziehen"};
        for(int i = 0; i < possible_actions.length; i++)
        {
          ContactActionBox.addItem(possible_actions[i]);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        Movement = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ContactObjectList = new javax.swing.JComboBox();
        ContactActionBox = new javax.swing.JComboBox();
        ApplyRules = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        RemoveButton = new javax.swing.JButton();
        ErrorLabel = new javax.swing.JLabel();
        MovementLabel = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        Movement.setText("Reichweite");
        Movement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovementActionPerformed(evt);
            }
        });

        jLabel1.setText("Bei Kontakt mit");

        ContactObjectList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ContactObjectList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactObjectListActionPerformed(evt);
            }
        });

        ContactActionBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ApplyRules.setText("Apply");
        ApplyRules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyRulesActionPerformed(evt);
            }
        });

        addButton.setText("+");

        RemoveButton.setText("-");
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });

        MovementLabel.setText("Bewegungsreichweite");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ContactObjectList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ContactActionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ApplyRules))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MovementLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Movement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MovementLabel)
                            .addComponent(Movement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ContactObjectList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContactActionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addButton)
                            .addComponent(RemoveButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ApplyRules)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MovementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovementActionPerformed

    }//GEN-LAST:event_MovementActionPerformed

    private void ApplyRulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyRulesActionPerformed

        
        
        //getting collision parameters
        ownObject = jList1.getSelectedValue().toString();
        collidesWith = ContactObjectList.getSelectedItem().toString();
        
        //Printing Errormessage when Objects collide with itself
        if(collidesWith.equals(ownObject))
        {
            ErrorLabel.setText("Collision with itself is not allowed.");
        }
        else
        {
            ErrorLabel.setText(" ");
        }
        
        collisionAction = ContactActionBox.getSelectedIndex();
        //debug output -dm
        System.out.println("object " + ownObject + " performs action " + 
                collisionAction + " on object " + collidesWith);
        
        
        
    }//GEN-LAST:event_ApplyRulesActionPerformed

    private void ContactObjectListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactObjectListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactObjectListActionPerformed

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApplyRules;
    private javax.swing.JComboBox ContactActionBox;
    private javax.swing.JComboBox ContactObjectList;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JTextField Movement;
    private javax.swing.JLabel MovementLabel;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
