/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pandora.TileMap;

import java.util.logging.Level;
import javax.swing.JOptionPane;
import pandora.ConstantStrings;

/**
 *
 * @author achillis
 */
public class OptionPanel1 extends javax.swing.JPanel {

    private MapEditor mapedit;
    /**
     * Creates new form OptionPanel1
     * @param mapedit
     */
    public OptionPanel1(MapEditor mapedit) {
        initComponents();
        this.mapedit = mapedit;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SetPoint = new javax.swing.JButton();
        XCord = new javax.swing.JTextField();
        YCord = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        jLabel2.setText("Map");

        jLabel3.setText("Start Point");

        SetPoint.setText("Setzen");
        SetPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetPointActionPerformed(evt);
            }
        });

        XCord.setText("X");
        XCord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XCordActionPerformed(evt);
            }
        });

        YCord.setText("Y");
        YCord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YCordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(XCord, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(YCord, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SetPoint))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(XCord, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YCord, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(SetPoint)
                .addContainerGap(107, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void XCordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XCordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XCordActionPerformed

    private void YCordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YCordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YCordActionPerformed

    private void SetPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetPointActionPerformed
      
        int xcord = Integer.parseInt(XCord.getText());
        int ycord = Integer.parseInt(YCord.getText());
        
        if(xcord < 42 && ycord < 42)
        {
           this.mapedit.getGame().setStartx_map(xcord);
           this.mapedit.getGame().setStarty_map(ycord);
        }
        else
        {
            JOptionPane.showMessageDialog(this, ConstantStrings.INVALID_VALUE ,
                    "Falsche Größe",JOptionPane.INFORMATION_MESSAGE);
            
        }
                
    }//GEN-LAST:event_SetPointActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SetPoint;
    private javax.swing.JTextField XCord;
    private javax.swing.JTextField YCord;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
